name: game_objects_devices
description: Device Flame components (server, computer, phone, IoT)
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.9.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.29.0
  flame_bloc: ^1.12.1
  app_lib_core:
    path: ../../app_lib/core
  app_lib_engine:
    path: ../../app_lib/engine
  app_widget_common:
    path: ../../app_widget/common
  game_bloc_world:
    path: ../../game_bloc/world

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^10.0.0
  mocktail: ^1.0.4
  flame_test: ^1.18.0
