name: game_widgets_hud
description: HUD widgets for game overlay
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.9.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  app_bloc_game:
    path: ../../app_bloc/game
  app_lib_core:
    path: ../../app_lib/core
  game_widgets_panels:
    path: ../panels

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^10.0.0
  mocktail: ^1.0.4
