name: app_database
version: 1.0.0
publish_to: "none"

environment:
  sdk: ">=3.8.0 <4.0.0"
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.26.2
  drift_flutter: ^0.2.5
  path_provider: ^2.1.5
  shared_preferences: ^2.5.4
  app_lib_engine:
    path: ../engine

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.26.2
  build_runner: ^2.4.15
  app_lib_core: any
