name: game_audio_sfx
description: Sound effects and audio for the game
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.9.0

resolution: workspace

dependencies:
  app_lib_core:
    path: ../../app_lib/core
  flame: ^1.29.0
  flame_audio: ^2.11.12
  logging: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
